tap 'buo/cask-upgrade'
tap 'homebrew/bundle'
tap "isen-ng/dotnet-sdk-versions"
tap 'koekeishiya/formulae'

cask_args appdir: '/Applications'

brew 'ag'
brew 'awscli'
brew 'awscli-local'
brew 'bat'
brew 'btop'
brew 'buf'
brew 'curl'
brew 'duf'
brew 'dust'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'go'
brew 'gnu-sed'
brew 'gping'
brew 'graphviz'
brew 'ipcalc'
brew 'jq'
brew 'lazygit'
brew 'lnav'
brew 'make'
brew 'mas'
brew 'node'
brew 'neovim'
brew 'okta-aws-cli'
brew 'openssh'
brew 'openssl'
brew 'procs'
brew 'protobuf'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ripgrep'
brew 'rustup'
brew 'sd'
brew 'skhd'
brew 'starship'
brew 'tldr'
brew 'tmux'
brew 'xh'
brew 'yt-dlp'
brew 'yabai'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'appcleaner'
cask 'docker'
cask 'font-jetbrains-mono-nerd-font'
cask 'fork'
cask 'ghostty'
cask 'google-drive'
cask 'intellij-idea'
cask 'keka'
cask 'mpv'
cask 'obsidian'
cask 'raycast'
cask 'rider'
cask 'shottr'
cask 'spotify'

mas 'Amphetamine', id: 937984704
mas 'Numbers', id: 409203825
mas 'Microsoft Remote Desktop', id: 1295203466
