#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Global settings
yabai -m config \
    active_window_opacity 1.0 \
    auto_balance off \
    mouse_follows_focus on \
    normal_window_opacity 0.90 \
    split_ratio 0.50 \
    window_opacity off \
    window_opacity_duration 0.0 \
    window_placement second_child \
    window_shadow on \
    window_topmost off \
    bottom_padding 10 \
    left_padding 10 \
    right_padding 10 \
    top_padding 10 \
    window_gap 10 \
    layout bsp

echo "yabai configuration loaded.."

# Applications
yabai -m rule --add app="^Preferences$" manage=off
yabai -m rule --add app="^Settings$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^TV$" manage=off

yabai -m rule --add app="^Arc$" space=^1
yabai -m rule --add app="^Alacritty$" space=^2
yabai -m rule --add app="^Rider$" space=3
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^Spotify$" space=9
